version: "3.7"
services:
  mariadb:
    image: mariadb:10.3.23
    environment:
      MYSQL_DATABASE: plaid
      MYSQL_USER: plaid_admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
  plaid:
    build: .
    environment:
      DB_USER: plaid_admin
      DB_PASSWORD: password
      DB_DATABASE: plaid
      DB_HOST: mariadb
    networks:
      - internal
    ports:
      - 81:80
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
networks:
  internal:
