/**
 * Created by morse on 7/27/16.
 */
var infoBarData = {
    builder: "<div>Time to build a Mission Specific Dictionary!</div><br> <div>Even after the discipline nodes, the PDS knows there will still be metadata specific to your mission.</div><br> <div>In this step, we add the final elements to your label. You will be building the label using the Label Design Tool MSD Builder.</div><br> <div>Remember, groups are collections of metadata around a common theme while attributes are pieces of metadata with only one value.</div><br>",
    discipline_nodes: "<div> <b> Now it's time to get specific! </b> </div><br> <div> The PDS has different requirements for different subject matters, and divides these into <b> disciplines </div> <br> <div> Hover over a discpline node to see it's description. </div><br> <div> <b> Tips from the label guru: </div> <br> <div> If your mission takes pictures, you need the imaging node </div> <br> <div>If your mission has a spacecraft or a rover, you need the geometry node </b></div>",
    export: "Export label as a file.",
    mission_specifics: "<div>Time to build a mission specific dictionary!</div><br> <div>Even after the discipline nodes, the PDS knows there will still be metadata specific to your mission.</div><br> <div>In this step, we add the final elements to your label. You will be building the label using the Label Design Tool MSD Builder.</div><br> <div>Remember, groups are collections of metadata around a common theme while attributes are pieces of metadata with only one value.</div><br>",
    product_type: "<div> <b>Time to pick a product type! </b> </div> <br> <div> The product type defines the general structure for your label based on the Planetary Data System’s most recent archiving standards. </div> <br> <div> Let us know what kind of data we're labeling. <b> Most of our users need labels for <em> Product Observational. </em> </b> <br> </div><br> <div>  Tips from our label guru:  </div> <br> <div> <b>Have a list of the items you want on your label! </div> <br> <div> Check out <a href=#> a sample label from another mission! </a> <br> </div><br> <div> Need Help? </div> <div>Find your answers in <a href=LDT_Product_Type.pdf> the full LDT guide for Product Type Selection </a> <br> </div> <br> "
};