<?php
/**
 * Created by PhpStorm.
 * User: morse
 * Date: 8/8/16
 * Time: 11:00 AM
 */
$data = '<Product_Observational>
    <Identification_Area>
        <logical_identifier></logical_identifier>
        <version_id></version_id>
        <title></title>
        <information_model_version></information_model_version>
        <product_class></product_class>
        <Alias_List>
            <Alias>
                <alternate_id></alternate_id>
                <alternate_title></alternate_title>
                <comment></comment>
            </Alias>
        </Alias_List>
        <Citation_Information>
            <author_list></author_list>
            <editor_list></editor_list>
            <publication_year></publication_year>
            <keyword></keyword>
            <description></description>
        </Citation_Information>
        <Modification_History>
            <Modification_Detail>
                <modification_date></modification_date>
                <version_id></version_id>
                <description></description>
            </Modification_Detail>
        </Modification_History>
    </Identification_Area>
    <Observation_Area>
        <comment></comment>
        <Time_Coordinates>
            <start_date_time></start_date_time>
            <stop_date_time></stop_date_time>
            <local_mean_solar_time></local_mean_solar_time>
            <local_true_solar_time></local_true_solar_time>
            <solar_longitude></solar_longitude>
        </Time_Coordinates>
        <Primary_Result_Summary>
            <type></type>
            <purpose></purpose>
            <data_regime></data_regime>
            <processing_level></processing_level>
            <processing_level_id></processing_level_id>
            <description></description>
            <Science_Facets>
                <wavelength_range></wavelength_range>
                <domain></domain>
                <discipline_name></discipline_name>
                <facet1></facet1>
                <subfacet1></subfacet1>
                <facet2></facet2>
                <subfacet2></subfacet2>
            </Science_Facets>
        </Primary_Result_Summary>
        <Investigation_Area>
            <name></name>
            <type></type>
            <Internal_Reference>
                <lid_reference></lid_reference>
                <reference_type></reference_type>
                <comment></comment>
            </Internal_Reference>
        </Investigation_Area>
        <Observing_System>
            <name></name>
            <description></description>
            <Observing_System_Component>
                <name></name>
                <type></type>
                <description></description>
                <Internal_Reference>
                    <lid_reference></lid_reference>
                    <reference_type></reference_type>
                    <comment></comment>
                </Internal_Reference>
                <External_Reference>
                    <doi></doi>
                    <reference_text></reference_text>
                    <description></description>
                </External_Reference>
            </Observing_System_Component>
        </Observing_System>
        <Target_Identification>
            <name></name>
            <alternate_designation></alternate_designation>
            <type></type>
            <description></description>
            <Internal_Reference>
                <lid_reference></lid_reference>
                <reference_type></reference_type>
                <comment></comment>
            </Internal_Reference>
        </Target_Identification>
        <Mission_Area>
            <ins:InsightClass></ins:InsightClass>
        </Mission_Area>
        <Discipline_Area></Discipline_Area>
    </Observation_Area>
    <Reference_List>
        <Internal_Reference>
            <lid_reference></lid_reference>
            <reference_type></reference_type>
            <comment></comment>
        </Internal_Reference>
        <External_Reference>
            <doi></doi>
            <reference_text></reference_text>
            <description></description>
        </External_Reference>
    </Reference_List>
    <File_Area_Observational>
        <File>
            <file_name></file_name>
            <local_identifier></local_identifier>
            <creation_date_time></creation_date_time>
            <file_size></file_size>
            <records></records>
            <md5_checksum></md5_checksum>
            <comment></comment>
        </File>
        <Array_1D>
            <name></name>
            <local_identifier></local_identifier>
            <offset></offset>
            <axes></axes>
            <axis_index_order></axis_index_order>
            <description></description>
            <Element_Array>
                <data_type></data_type>
                <unit></unit>
                <scaling_factor></scaling_factor>
                <value_offset></value_offset>
            </Element_Array>
            <Axis_Array>
                <axis_name></axis_name>
                <local_identifier></local_identifier>
                <elements></elements>
                <unit></unit>
                <sequence_number></sequence_number>
                <Band_Bin_Set>
                    <Band_Bin>
                        <band_number></band_number>
                        <band_width></band_width>
                        <center_wavelength></center_wavelength>
                        <detector_number></detector_number>
                        <filter_number></filter_number>
                        <grating_position></grating_position>
                        <original_band></original_band>
                        <standard_deviation></standard_deviation>
                        <scaling_factor></scaling_factor>
                        <value_offset></value_offset>
                    </Band_Bin>
                </Band_Bin_Set>
            </Axis_Array>
            <Special_Constants>
                <saturated_constant></saturated_constant>
                <missing_constant></missing_constant>
                <error_constant></error_constant>
                <invalid_constant></invalid_constant>
                <unknown_constant></unknown_constant>
                <not_applicable_constant></not_applicable_constant>
                <valid_maximum></valid_maximum>
                <high_instrument_saturation></high_instrument_saturation>
                <high_representation_saturation></high_representation_saturation>
                <valid_minimum></valid_minimum>
                <low_instrument_saturation></low_instrument_saturation>
                <low_representation_saturation></low_representation_saturation>
            </Special_Constants>
            <Object_Statistics>
                <local_identifier></local_identifier>
                <maximum></maximum>
                <minimum></minimum>
                <mean></mean>
                <standard_deviation></standard_deviation>
                <bit_mask></bit_mask>
                <median></median>
                <md5_checksum></md5_checksum>
                <maximum_scaled_value></maximum_scaled_value>
                <minimum_scaled_value></minimum_scaled_value>
                <description></description>
            </Object_Statistics>
        </Array_1D>
    </File_Area_Observational>
    <File_Area_Observational_Supplemental>
        <File>
            <file_name></file_name>
            <local_identifier></local_identifier>
            <creation_date_time></creation_date_time>
            <file_size></file_size>
            <records></records>
            <md5_checksum></md5_checksum>
            <comment></comment>
        </File>
        <Array_1D>
            <name></name>
            <local_identifier></local_identifier>
            <offset></offset>
            <axes></axes>
            <axis_index_order></axis_index_order>
            <description></description>
            <Element_Array>
                <data_type></data_type>
                <unit></unit>
                <scaling_factor></scaling_factor>
                <value_offset></value_offset>
            </Element_Array>
            <Axis_Array>
                <axis_name></axis_name>
                <local_identifier></local_identifier>
                <elements></elements>
                <unit></unit>
                <sequence_number></sequence_number>
                <Band_Bin_Set>
                    <Band_Bin>
                        <band_number></band_number>
                        <band_width></band_width>
                        <center_wavelength></center_wavelength>
                        <detector_number></detector_number>
                        <filter_number></filter_number>
                        <grating_position></grating_position>
                        <original_band></original_band>
                        <standard_deviation></standard_deviation>
                        <scaling_factor></scaling_factor>
                        <value_offset></value_offset>
                    </Band_Bin>
                </Band_Bin_Set>
            </Axis_Array>
            <Special_Constants>
                <saturated_constant></saturated_constant>
                <missing_constant></missing_constant>
                <error_constant></error_constant>
                <invalid_constant></invalid_constant>
                <unknown_constant></unknown_constant>
                <not_applicable_constant></not_applicable_constant>
                <valid_maximum></valid_maximum>
                <high_instrument_saturation></high_instrument_saturation>
                <high_representation_saturation></high_representation_saturation>
                <valid_minimum></valid_minimum>
                <low_instrument_saturation></low_instrument_saturation>
                <low_representation_saturation></low_representation_saturation>
            </Special_Constants>
            <Object_Statistics>
                <local_identifier></local_identifier>
                <maximum></maximum>
                <minimum></minimum>
                <mean></mean>
                <standard_deviation></standard_deviation>
                <bit_mask></bit_mask>
                <median></median>
                <md5_checksum></md5_checksum>
                <maximum_scaled_value></maximum_scaled_value>
                <minimum_scaled_value></minimum_scaled_value>
                <description></description>
            </Object_Statistics>
        </Array_1D>
    </File_Area_Observational_Supplemental>
</Product_Observational>';
$path = "/tmp/";
$storageDir = "ldt_labels";
if (!file_exists($path.$storageDir)){
    mkdir($path.$storageDir);
}
$file = tempnam($path.$storageDir, "label_template_");
file_put_contents($file, $data);
chmod($file, 0750);
echo $file;